// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutContributors: typeof import('./src/components/about/AboutContributors.vue')['default']
    AboutOptions: typeof import('./src/components/about/AboutOptions.vue')['default']
    AboutSillage: typeof import('./src/components/about/AboutSillage.vue')['default']
    FunctionEntrance: typeof import('./src/components/index/FunctionEntrance.vue')['default']
    GradeList: typeof import('./src/components/index/GradeList.vue')['default']
    LanguageSwitch: typeof import('./src/components/LanguageSwitch.vue')['default']
    NDivider: typeof import('naive-ui')['NDivider']
    NSpace: typeof import('naive-ui')['NSpace']
    PcCourseTitle: typeof import('./src/components/Course/PcCourseTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SillageTitle: typeof import('./src/components/SillageTitle.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    UserBookmark: typeof import('./src/components/index/UserBookmark.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}

export {}
